src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createad_at = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?bool $isFovory = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    private ?Category $category = null;

    #[ORM\Column(length: 255)]
    private ?string $localite = null;

    #[ORM\Column(nullable: true)]
    private ?int $nb = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreateadAt(): ?\DateTimeImmutable
    {
        return $this->createad_at;
    }

    public function setCreateadAt(\DateTimeImmutable $createad_at): self
    {
        $this->createad_at = $createad_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function isIsFovory(): ?bool
    {
        return $this->isFovory;
    }

    public function setIsFovory(bool $isFovory): self
    {
        $this->isFovory = $isFovory;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getLocalite(): ?string
    {
        return $this->localite;
    }

    public function setLocalite(string $localite): self
    {
        $this->localite = $localite;

        return $this;
    }

    public function getNb(): ?int
    {
        return $this->nb;
    }

    public function setNb(?int $nb): self
    {
        $this->nb = $nb;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('slug')
            ->add('createad_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/annonces')]
class PostController extends AbstractController
{
    public function __construct(private EntityManagerInterface $em)
    {
    }

    #[Route('/', name: 'app_post_index', methods: ['GET'])]
    public function index(PostRepository $postRepository): Response
    {
        return $this->render('post/index.html.twig', [
            'posts' => $postRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_post_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PostRepository $postRepository): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $postRepository->save($post, true);

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('post/new.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_show', methods: ['GET'])]
    public function show(Post $post): Response
    {
        return $this->render('post/show.html.twig', [
            'post' => $post,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_post_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Post $post, PostRepository $postRepository): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $postRepository->save($post, true);

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('post/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_delete', methods: ['POST'])]
    public function delete(Request $request, Post $post, PostRepository $postRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $postRepository->remove($post, true);
        }

        return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
    }



}

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('app_post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn">Delete</button>
</form>

templates/post/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/post/annonces_favories.html.twig
{% extends "base.html.twig" %}
{% block title %} Nos ~ favories {%  endblock %}

{% block body %}
<div class="row" style="margin-top: 300px !important;">
    {% include 'post/favory.html.twig' %}
</div>

{% endblock %}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post{% endblock %}

{% block body %}
    <h1>Edit Post</h1>

    {{ include('post/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_post_index') }}">back to list</a>

    {{ include('post/_delete_form.html.twig') }}
{% endblock %}

templates/post/favory.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post index{% endblock %}

{% block body %}

    <h2 class="text-center" id="vos_favory">Nos appartements favoris</h2>
    <div class="row">
        {% for p in post %}
            <div class="col-sm-12 col-lg-6">
                <div class="card bg-light mb-3">
                    <div class="card-header text-center">
                        {% if p.nb >0 %}
                            {{ p.nb}} Appartement(s) disponible(s).
                        {% endif %}
                        <br>
                        <strong>{{ (p.prix / 100) | number_format(0,',','.')}}  FCFA /mois</strong>
                        <br>
                        Publié le
                        <span class="bg-secondary text-light"> {{ p.createadAt ? p.createadAt|date('d/m/Y') : '' }}</span>
                        <img class="img-fluid" alt="" style="height: 150px; width: 100%; display: block;" src="/uploads/images/posts/{{ p.image }}">
                        <div class="card-body">
                            <h4 class="card-title">
                                {{ p.title }} à {{ p.localite }}
                            </h4>
                            <p class="card-text">
                                {{ p.description| raw}}
                            </p>
                            <a class="btn btn-primary" href="{{ path('app_post_show',{'id': p.id}) }}"> <i class="fa-regular fa-eye fa-2xl bg-secondary"></i> Voir cette annonce
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post index{% endblock %}

{% block body %}

<h2 class="text-center">Nos appartements stars</h2>
<div class="row favory">
    {% for p in posts %}
    <div class="col-sm-12">
        <div class="card bg-light mb-3">
            <div class="card-header text-center">
                {% if p.nb >0 %}
                    {{ p.nb}} Appartement(s) disponible(s).
                {% endif %}
                <br>
                    <strong>{{ (p.prix / 100) | number_format(0,',','.')}}  FCFA /mois</strong>
                    <br>
                Publié le
                <span class="bg-secondary text-light"> {{ p.createadAt ? p.createadAt|date('d/m/Y') : '' }}</span>
                    <img alt="" style="height: 150px; width: 100%; display: block;" src="/uploads/images/posts/{{ p.image }}">
                    <div class="card-body">
                        <h4 class="card-title">
                           {{ p.title }}
                        </h4>
                        <p class="card-text">
                           {{ p.description| raw}}
                        </p>
                        <a class="btn btn-primary" href="{{ path('app_post_show',{'id': p.id}) }}">
                            <i class="fa-regular fa-eye fa-2xl text-light"> </i>
                            Voir cette annonce
                        </a>
                    </div>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>

{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Post{% endblock %}

{% block body %}
    <h1>Create new Post</h1>

    {{ include('post/_form.html.twig') }}

    <a href="{{ path('app_post_index') }}">back to list</a>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post{% endblock %}

{% block body %}
    <h1 class="text-center alert alert-warning">Annonces "{{ post.slug }}"</h1>
    <div class="col-sm-12">
        <div class="card bg-light mb-3">
            <div class="card-header text-center">
                <strong>{{ (post.prix / 100) | number_format(0,',','.')}} FCFA /mois</strong>
                <br>
                Publié le
                <span class="bg-primary text-light"> {{ post.createadAt ? post.createadAt|date('d/m/Y') : '' }}</span>
                <img style="height: 300px; width: 100%; display: block;" src="/uploads/images/posts/{{ post.image }}" alt="Image de l'annonce">
                <div class="card-body">
                    <h4 class="card-title">
                        {{ post.title }} à {{ post.localite }}
                    </h4>
                    <p class="card-text">
                        {{ post.description| raw}}
                    </p>
                <a href="{{ path('app_post_index') }}" class="btn btn-primary">Retour sur les annonces</a>

                </div>
            </div>
        </div>
    </div>


{% endblock %}